### ISSUE TITLE
AdminMetaWebhookOptionsSetRequest & AdminMetaWebhookOptionsGetRequest WebhookOptions

### ISSUE THREAD

**Issue by woodspire** [CometBackup/comet-php-sdk#4]
Why is it specified that WebhookOptions parameter (or returned value) Must be a Dictionnary of WebhookOption ?
Why not a list ?

I don't see why a key is required for each WebhookOption.

The value is json encoded so I think this:

[{"url" : 'https://blablabla', "WhiteList..": [4000,4100]}, {"url" : 'https://another', "WhiteList..": [4101,4102]}]

is better than this:

{ "unused key 1": {"url" : 'https://blablabla', "WhiteList..": [4000,4100]}, "unused key 2" : {"url" : 'https://another', "WhiteList..": [4101,4102]} }

**Comment by mason-cometbackup** [comment]
It's useful for a few different reasons:

- The Comet Server can more easily detect changes to individual endpoints. If you change only a single one of your webhook targets, then the other targets don't need their message queue to be torn down and recreated
- If a webhook message fails, we can report the ID of which target had failed
- If multiple API systems are all registering webhooks (e.g. an eCommerce integration, a CRM integration, and an ERP integration) - as long as everyone uses their own generated keys, it's easy to keep them apart

And these features haven't landed yet in 20.8.x Comet Server versions, but in the future:
- We can report on statistics, queue length, etc on a per-ID basis
- It's helpful for the web GUI, to manage adding and removing single entries

Regardless, we're committed to maintaining backwards-compatibility for the API, so we will keep it this way. If you don't have any particularly special use for the keys, then you could use a GUID, or a constant string (e.g. "MY_BACKEND_SYSTEM").

**Comment by woodspire** [comment]
Great explanation. Thanks. Closing since nothing is broken.
